{ haskellPackages }:

with haskellPackages; [
  # additional packages (from stackage)
  AC-Vector
  BlastHTTP
  BlogLiterately
  BlogLiterately-diagrams
  Boolean
  BoundedChan
  Cabal
  Cabal-ide-backend
  Chart
  Chart-cairo
  ChasingBottoms
  DAV
  DRBG
  Decimal
  Diff
  FenwickTree
  FontyFruity
  GLURaw
  GLUT
  GenericPretty
  Glob
  GraphSCC
  HCodecs
  HList
  HStringTemplate
  HTF
  HTTP
  HUnit
  HaTeX
  HaXml
  HandsomeSoup
  HaskellNet
  HsOpenSSL
  IfElse
  JuicyPixels
  List
  ListLike
  MemoTrie
  MissingH
  MonadCatchIO-transformers
  MonadPrompt
  MonadRandom
  NumInstances
  ObjectName
  Octree
  OpenGL
  OpenGLRaw
  PSQueue
  QuasiText
  QuickCheck
  RSA
  Rasterific
  ReadArgs
  RefSerialize
  SHA
  SafeSemaphore
  Spock
  Spock-digestive
  Spock-worker
  StateVar
  TCache
  Unixutils
  Workflow
  X11
  Yampa
  YampaSynth
  abstract-deque
  abstract-par
  accelerate
  ace
  action-permutations
  active
  ad
  adjunctions
  aeson
  aeson-better-errors
  aeson-pretty
  aeson-qq
  aeson-schema
  aeson-utils
  agentx
  alarmclock
  alex
  amazonka
  amazonka-autoscaling
  amazonka-cloudformation
  amazonka-cloudfront
  amazonka-cloudhsm
  amazonka-cloudsearch
  amazonka-cloudsearch-domains
  amazonka-cloudtrail
  amazonka-cloudwatch
  amazonka-cloudwatch-logs
  amazonka-codedeploy
  amazonka-cognito-identity
  amazonka-cognito-sync
  amazonka-config
  amazonka-core
  amazonka-datapipeline
  amazonka-directconnect
  amazonka-dynamodb
  amazonka-ec2
  amazonka-ecs
  amazonka-elasticache
  amazonka-elasticbeanstalk
  amazonka-elastictranscoder
  amazonka-elb
  amazonka-emr
  amazonka-glacier
  amazonka-iam
  amazonka-importexport
  amazonka-kinesis
  amazonka-kms
  amazonka-lambda
  amazonka-ml
  amazonka-opsworks
  amazonka-rds
  amazonka-redshift
  amazonka-route53
  amazonka-route53-domains
  amazonka-s3
  amazonka-sdb
  amazonka-ses
  amazonka-sns
  amazonka-sqs
  amazonka-ssm
  amazonka-storagegateway
  amazonka-sts
  amazonka-support
  amazonka-swf
  amazonka-workspaces
  amqp
  annotated-wl-pprint
  ansi-terminal
  ansi-wl-pprint
  appar
  applicative-quoters
  approximate
  arbtt
  arrow-list
  asciidiagram
  asn1-encoding
  asn1-parse
  asn1-types
  async
  attoparsec
  attoparsec-enumerator
  attoparsec-expr
  authenticate
  authenticate-oauth
  auto
  auto-update
  aws
  bake
  bank-holidays-england
  base-compat
  base-orphans
  base-prelude
  base-unicode-symbols
  base16-bytestring
  base32string
  base58string
  base64-bytestring
  base64-string
  basic-prelude
  bcrypt
  bencode
  bifunctors
  binary-conduit
  binary-list
  bindings-DSL
  bioace
  bioalign
  biocore
  biofasta
  biofastq
  biopsl
  bits
  bitwise
  blastxml
  blaze-builder
  blaze-builder-enumerator
  blaze-html
  blaze-markup
  blaze-textual
  bloodhound
  bloomfilter
  bmp
  bool-extras
  boolsimplifier
  bound
  broadcast-chan
  bson
  btrfs
  buffer-builder
  bumper
  byteable
  bytedump
  byteorder
  bytes
  bytestring-builder
  bytestring-conversion
  bytestring-lexing
  bytestring-mmap
  bytestring-progress
  bytestring-trie
  bzlib
  bzlib-conduit
  c2hs
  cabal-debian
  cabal-file-th
  cabal-install
  cabal-rpm
  cabal-src
  cairo
  cartel
  case-insensitive
  cases
  cassava
  cereal
  cereal-conduit
  cereal-vector
  cgi
  charset
  check-email
  checkers
  chell
  chell-quickcheck
  chunked-data
  cipher-aes
  cipher-aes128
  cipher-blowfish
  cipher-camellia
  cipher-des
  cipher-rc4
  circle-packing
  # clash-ghc
  # clash-lib -- depends on singletons
  # clash-prelude
  # clash-systemverilog
  # clash-verilog -- depends on singletons
  # clash-vhdl
  classy-prelude
  classy-prelude-conduit
  classy-prelude-yesod
  clay
  clientsession
  clock
  cmark
  cmdargs
  code-builder
  codex
  colour
  comonad
  comonad-transformers
  comonads-fd
  compdata
  composition
  composition-extra
  compressed
  concatenative
  concurrent-extra
  concurrent-supply
  conduit
  conduit-combinators
  conduit-extra
  configurator
  connection
  constraints
  # consul-haskell -- tests fail
  containers-unicode-symbols
  contravariant
  control-bool
  control-monad-free
  control-monad-loop
  convertible
  cookie
  country-codes
  courier
  cpphs
  cprng-aes
  cpu
  cql
  cql-io
  crackNum
  criterion
  cron
  crypto-api
  crypto-api-tests
  crypto-cipher-tests
  crypto-cipher-types
  crypto-numbers
  crypto-pubkey
  crypto-pubkey-types
  crypto-random
  crypto-random-api
  cryptocipher
  cryptohash
  cryptohash-conduit
  cryptohash-cryptoapi
  cryptol
  cryptonite
  css-text
  csv
  csv-conduit
  cubicspline
  curl
  data-accessor
  data-accessor-mtl
  data-binary-ieee754
  data-default
  data-default-class
  data-default-instances-base
  data-default-instances-containers
  data-default-instances-dlist
  data-default-instances-old-locale
  data-inttrie
  data-lens-light
  data-memocombinators
  data-ordlist
  data-reify
  datadog
  dbus
  debian
  deepseq-generics
  derive
  descriptive
  diagrams
  diagrams-builder
  diagrams-cairo
  diagrams-contrib
  diagrams-core
  diagrams-html5
  diagrams-lib
  diagrams-postscript
  diagrams-rasterific
  diagrams-solve
  diagrams-svg
  digest
  digestive-functors
  dimensional
  direct-sqlite
  directory-tree
  disk-free-space
  distributive
  djinn-ghc
  djinn-lib
  dlist
  dlist-instances
  dns
  doctest
  double-conversion
  dual-tree
  easy-file
  ede
  edit-distance
  editor-open
  effect-handlers
  either
  elm-core-sources
  email-validate
  enclosed-exceptions
  engine-io
  engine-io-growler
  entropy
  enumerator
  eq
  erf
  errors
  esqueleto
  exception-mtl
  exception-transformers
  exceptional
  exceptions
  executable-hash
  executable-path
  expiring-cache-map
  extensible-exceptions
  extra
  fast-logger
  fay
  fay-base
  fay-builder
  fay-dom
  fay-jquery
  fay-text
  fay-uri
  fb
  fb-persistent
  fclabels
  fdo-notify
  feature-flags
  feed
  fgl
  file-embed
  file-location
  filemanip
  fingertree
  fingertree-psqueue
  fixed
  fixed-list
  flexible-defaults
  flock
  flow
  flowdock
  fmlist
  focus
  foldl
  force-layout
  foreign-store
  formatting
  free
  frisby
  fsnotify
  fuzzcheck
  gd
  generic-aeson
  generic-deriving
  generic-xmlpickler
  generics-sop
  getopt-generics
  ghc-events
  ghc-mtl
  ghc-paths
  ghc-syb-utils
  ghc-tcplugins-extra
  ghc-typelits-natnormalise
  ghcid
  gio
  gipeda
  git-annex
  git-embed
  gitlib
  gitlib-libgit2
  gitlib-test
  gitrev
  gl
  glib
  gnuidn
  gnutls
  graph-core
  graph-wrapper
  graphs
  gravatar
  groundhog
  groundhog-mysql
  groundhog-postgresql
  groundhog-sqlite
  groundhog-th
  groupoids
  groups
  growler
  gsasl
  gtk
  gtk2hs-buildtools
  gtk3
  hPDB
  hPDB-examples
  hackage-db
  haddock-api
  haddock-library
  hakyll
  half
  hamlet
  happstack-server
  happy
  hashable
  hashable-extras
  hashmap
  hashtables
  haskeline
  haskell-lexer
  # haskell-names -- tests fail to build
  haskell-packages
  haskell-spacegoo
  haskell-src
  haskell-src-exts
  haskell-src-meta
  haskintex
  hasql
  hasql-backend
  hasql-postgres
  hastache
  haxr
  hdaemonize
  hdevtools
  hdocs
  heap
  heaps
  hebrew-time
  hedis
  heist
  here
  heredoc
  hex
  hexpat
  hexstring
  hflags
  highlighting-kate
  hindent
  hinotify
  hint
  histogram-fill
  hit
  hjsmin
  hledger
  hledger-lib
  hledger-web
  hlibgit2
  hlint
  hmatrix
  hmatrix-gsl
  # hmatrix-gsl-stats -- fails to build
  hmatrix-repa
  hoauth2
  holy-project
  hoogle
  hostname
  hostname-validate
  hourglass
  # hpc-coveralls -- linker failure
  hs-bibutils
  hscolour
  hse-cpp
  hsemail
  # hsignal -- depends on hmatrix-gsl-stats
  hslogger
  hslua
  hspec
  hspec-attoparsec
  hspec-contrib
  hspec-core
  hspec-discover
  hspec-expectations
  hspec-jenkins
  hspec-meta
  hspec-smallcheck
  hspec-snap
  hspec-wai
  hspec-wai-json
  # hstatistics -- depends on hmatrix-gsl-stats
  hsyslog
  html
  html-conduit
  http-accept
  http-client
  http-client-tls
  http-common
  http-conduit
  http-date
  http-media
  http-reverse-proxy
  http-streams
  http-types
  http2
  hweblib
  hxt
  hxt-charproperties
  hxt-css
  hxt-curl
  hxt-expat
  hxt-http
  hxt-pickle-utils
  hxt-regex-xmlschema
  hxt-relaxng
  hxt-tagsoup
  hxt-unicode
  # hyperloglog -- fails to build
  hyphenation
  ide-backend
  ide-backend-common
  ide-backend-rts
  ide-backend-server
  ieee754
  imagesize-conduit
  immortal
  # include-file -- fails to build
  incremental-parser
  indents
  ini
  integration
  interpolate
  interpolatedstring-perl6
  intervals
  io-choice
  io-manager
  io-memoize
  io-streams
  iproute
  islink
  iterable
  jmacro
  jmacro-rpc
  jmacro-rpc-happstack
  jmacro-rpc-snap
  jose-jwt
  js-flot
  js-jquery
  json
  json-autotype
  json-builder
  json-schema
  jwt
  kan-extensions
  kdt
  keter
  keys
  kmeans
  koofr-client
  kure
  language-c
  language-c-quote
  language-ecmascript
  language-glsl
  language-haskell-extract
  language-java
  language-javascript
  largeword
  lattices
  lazy-csv
  lca
  lens
  lens-action
  lens-aeson
  lens-family
  lens-family-core
  lens-family-th
  lens-simple
  lexer-applicative
  lhs2tex
  libgit
  libnotify
  librato
  libxml-sax
  lifted-async
  lifted-base
  linear
  linear-accelerate
  linux-file-extents
  linux-namespaces
  list-fusion-probe
  list-t
  loch-th
  log-domain
  logging-facade
  logict
  loop
  lrucache
  lucid
  lucid-svg
  lzma-conduit
  machines
  machines-directory
  machines-io
  machines-process
  mainland-pretty
  managed
  mandrill
  # mangopay
  map-syntax
  markdown
  markdown-unlit
  markup
  math-functions
  matrix
  maximal-cliques
  mbox
  memoize
  memory
  mersenne-random-pure64
  messagepack
  messagepack-rpc
  metrics
  mime-mail
  mime-mail-ses
  mime-types
  missing-foreign
  mmap
  mmorph
  monad-control
  monad-coroutine
  monad-extras
  monad-journal
  monad-logger
  monad-logger-json
  monad-logger-syslog
  monad-loops
  monad-par
  monad-par-extras
  monad-parallel
  monad-primitive
  monad-products
  monad-skeleton
  monad-st
  monad-stm
  monad-unlift
  monadLib
  monadcryptorandom
  monadic-arrays
  monads-tf
  mongoDB
  mono-traversable
  monoid-extras
  monoid-subclasses
  mtl
  mtl-compat
  mtl-prelude
  mtlparse
  multiarg
  multimap
  multipart
  mutable-containers
  mwc-random
  mysql
  mysql-simple
  nanospec
  nats
  ndjson-conduit
  neat-interpolation
  nested-routes
  netwire
  network
  # network-anonymous-i2p -- tests fail
  network-anonymous-tor
  network-attoparsec
  network-conduit
  network-conduit-tls
  network-info
  network-multicast
  network-protocol-xmpp
  network-simple
  network-transport
  network-uri
  newtype
  newtype-generics
  nonce
  nsis
  numbers
  numeric-extras
  numtype
  objective
  old-locale
  old-time
  opaleye
  openpgp-asciiarmor
  openssl-streams
  operational
  options
  optparse-applicative
  optparse-simple
  osdkeys
  pager
  pagerduty
  palette
  pandoc
  pandoc-citeproc
  pandoc-types
  pango
  parallel
  parallel-io
  parseargs
  parsec
  parsers
  partial-handler
  path
  path-pieces
  patience
  pcre-heavy
  pcre-light
  pdfinfo
  pem
  persistent
  persistent-mongoDB
  persistent-mysql
  persistent-postgresql
  persistent-refs
  persistent-sqlite
  persistent-template
  phantom-state
  picoparsec
  pipes
  pipes-aeson
  pipes-attoparsec
  pipes-binary
  pipes-bytestring
  pipes-concurrency
  pipes-group
  pipes-http
  pipes-network
  pipes-parse
  pipes-safe
  pipes-text
  pipes-wai
  placeholders
  plot
  plot-gtk
  plot-gtk3
  pointed
  poly-arity
  polyparse
  posix-realtime
  post-mess-age
  postgresql-binary
  postgresql-libpq
  postgresql-simple
  pred-trie
  prednote
  prefix-units
  prelude-extras
  presburger
  pretty-class
  pretty-show
  prettyclass
  primes
  primitive
  process-extras
  product-profunctors
  # profunctor-extras -- fails to build
  profunctors
  project-template
  psqueues
  pure-io
  pureMD5
  pwstore-fast
  quandl-api
  quickcheck-assertions
  quickcheck-instances
  quickcheck-io
  quickcheck-unicode
  rainbow
  random
  random-fu
  random-shuffle
  random-source
  rasterific-svg
  raw-strings-qq
  redis-io
  redis-resp
  reducers
  ref-fd
  reflection
  regex-applicative
  regex-base
  regex-compat
  regex-pcre
  regex-pcre-builtin
  regex-posix
  regex-tdfa
  regex-tdfa-rc
  regexpr
  repa
  repa-algorithms
  repa-devil
  repa-io
  reroute
  resource-pool
  resourcet
  rest-client
  rest-core
  rest-gen
  rest-happstack
  rest-snap
  rest-stringmap
  rest-types
  rest-wai
  # rethinkdb-client-driver -- tests fail
  retry
  rev-state
  rfc5051
  runmemo
  rvar
  safe
  safecopy
  sandi
  sbv
  scalpel
  scientific
  scotty
  sdl2
  # second-transfer -- linker failure
  securemem
  semigroupoid-extras
  semigroupoids
  semigroups
  semver
  sendfile
  seqloc
  serf
  servant
  servant-client
  servant-docs
  servant-jquery
  servant-server
  set-extra
  set-monad
  setenv
  setlocale
  shake
  shake-language-c
  shakespeare
  shakespeare-text
  shell-conduit
  shelltestrunner
  shelly
  silently
  simple-reflect
  simple-sendfile
  # singletons -- broken on 7.10.1, needs 7.10.2 when it is released
  siphash
  skein
  slave-thread
  smallcheck
  smoothie
  smtLib
  snap
  snap-core
  snap-server
  snaplet-fay
  snmp
  snowflake
  socket-io
  socks
  sodium
  sourcemap
  speculation
  sphinx
  splice
  split
  spoon
  sqlite-simple
  srcloc
  stackage
  stackage-build-plan
  stackage-cabal
  stackage-cli
  stackage-install
  stackage-metadata
  stackage-sandbox
  stackage-setup
  stackage-types
  stackage-update
  stackage-upload
  stateref
  statestack
  static-canvas
  statistics
  statistics-linreg
  stm
  stm-chans
  stm-conduit
  stm-containers
  stm-delay
  stm-stats
  storable-complex
  storable-endian
  streaming-commons
  strict
  string-conversions
  stringable
  stringbuilder
  stringsearch
  stylish-haskell
  svg-tree
  swagger
  syb
  symbol
  system-fileio
  system-filepath
  system-posix-redirect
  tabular
  tagged
  tagged-binary
  tagshare
  tagsoup
  tagstream-conduit
  tar
  tardis
  tasty
  tasty-ant-xml
  tasty-golden
  tasty-hspec
  tasty-hunit
  tasty-kat
  tasty-quickcheck
  tasty-rerun
  tasty-silver
  tasty-smallcheck
  tasty-th
  temporary
  temporary-rc
  terminal-progress-bar
  terminal-size
  terminfo
  test-framework
  test-framework-hunit
  test-framework-quickcheck2
  test-framework-th
  testing-feat
  texmath
  text
  text-binary
  text-format
  text-icu
  text-manipulate
  tf-random
  th-desugar
  th-expand-syns
  th-extras
  th-lift
  th-orphans
  th-reify-many
  threads
  through-text
  thumbnail-plus
  # thyme -- building tests fails
  time-compat
  time-lens
  time-locale-compat
  timezone-olson
  timezone-series
  tinylog
  tls
  tls-debug
  torrent
  tostring
  transformers-base
  transformers-compat
  traverse-with-class
  tree-view
  trifecta
  tttool
  tuples-homogenous-h98
  turtle
  type-eq
  # type-list -- depends on singletons
  unbound-generics
  unbounded-delays
  union-find
  uniplate
  unix-compat
  unix-time
  unordered-containers
  uri-bytestring
  uri-encode
  uri-templater
  url
  urlpath
  users
  users-postgresql-simple
  users-test
  utf8-light
  utf8-string
  uu-interleaved
  uu-parsinglib
  uuid
  uuid-types
  vault
  vector
  vector-algorithms
  vector-binary-instances
  vector-buffer
  vector-instances
  vector-space
  vector-space-points
  vector-th-unbox
  vhd
  void
  wai
  wai-app-static
  wai-conduit
  # wai-cors -- tests fail
  # wai-eventsource -- fails to build
  wai-extra
  wai-handler-launch
  wai-logger
  # wai-middleware-consul
  wai-middleware-crowd
  wai-middleware-static
  # wai-predicates -- depends on singletons
  wai-route
  wai-routes
  # wai-routing -- depends on singletons
  wai-util
  wai-websockets
  # waitra -- test fail
  warp
  warp-tls
  web-fpco
  webpage
  websockets
  witherable
  wizards
  wl-pprint
  wl-pprint-extras
  wl-pprint-terminfo
  wl-pprint-text
  word8
  wordpass
  wrap
  wreq
  x509
  x509-store
  x509-system
  x509-validation
  xenstore
  xhtml
  xml
  xml-conduit
  xml-hamlet
  xml-lens
  xml-to-json
  xml-to-json-fast
  xml-types
  xmlgen
  xmlhtml
  xss-sanitize
  yackage
  yaml
  yesod
  yesod-auth
  yesod-auth-deskcom
  yesod-auth-fb
  yesod-auth-hashdb
  yesod-auth-oauth
  yesod-auth-oauth2
  yesod-bin
  yesod-core
  yesod-default
  # yesod-eventsource -- depends on wai-eventsource
  yesod-fay
  yesod-fb
  yesod-form
  yesod-gitrepo
  yesod-gitrev
  # yesod-mangopay -- depends on shakespeare-css
  yesod-newsfeed
  yesod-persistent
  yesod-sitemap
  yesod-static
  yesod-test
  yesod-text-markdown
  yesod-websockets
  # zeromq4-haskell -- zeromq fails to build
  zip-archive
  zlib
  zlib-bindings
  zlib-enum
  zlib-lens
]
