#!/usr/bin/env bash


halcyon_mueval () {
  local ghc_path sandbox_path
  ghc_path=$( find "${HALCYON_BASE}/ghc" -name 'package.conf.d' 2>'/dev/null' ) || true
  sandbox_path=$( find "${HALCYON_BASE}/sandbox" -name '*-packages.conf.d' 2>'/dev/null' ) || true

  GHC_PACKAGE_PATH="${ghc_path}:${sandbox_path}" \
    mueval.original "$@"
}


halcyon_mueval "$@"
